spring:
  datasource:
    # url: jdbc:postgresql://${PRODUCT_PG_HOST:localhost}:${PRODUCT_PG_PORT:5432}/${PRODUCT_PG_DATABASE:postgres}
    # username: ${PRODUCT_PG_USERNAME:root}
    # password: ${PRODUCT_PG_PASSWORD:root}
    url: jdbc:postgresql://localhost:5432/order
    # username: ${PRODUCT_PG_USERNAME:root}
    # password: ${PRODUCT_PG_PASSWORD:root}
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    # database: postgresql
    # database-platform: org.hibernate.dialect.PostgreSQLDialect
    # show-sql: true
    properties:
      hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${ORDER_SERVICE_PORT:8633} 