spring:
  datasource:
    # url: jdbc:postgresql://${PRODUCT_PG_HOST:localhost}:${PRODUCT_PG_PORT:5432}/${PRODUCT_PG_DATABASE:postgres}
    # username: ${PRODUCT_PG_USERNAME:root}
    # password: ${PRODUCT_PG_PASSWORD:root}
    url: jdbc:postgresql://localhost:5432/order
    # username: ${PRODUCT_PG_USERNAME:root}
    # password: ${PRODUCT_PG_PASSWORD:root}
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    # database: postgresql
    # database-platform: org.hibernate.dialect.PostgreSQLDialect
    # show-sql: true
    properties:
      hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
    
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.diploma.order_service.models.order.OrderConfirmation


# URLs for open feign via api gateway
application:
    config:
        customer-url: http://${API_GATEWAY_HOST:localhost}:${API_GATEWAY_PORT:8222}/api/v1/customer
        product-url: http://${API_GATEWAY_HOST:localhost}:${API_GATEWAY_PORT:8222}/api/v1/product
        payment-url: http://${API_GATEWAY_HOST:localhost}:${API_GATEWAY_PORT:8222}/api/v1/payment
server:
  port: ${ORDER_SERVICE_PORT:8633} 