spring:
  datasource:
    url: jdbc:postgresql://${PRODUCT_PG_HOST:localhost}:${PRODUCT_PG_PORT:5432}/product
    username: ${PRODUCT_PG_USERNAME:root}
    password: ${PRODUCT_PG_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    baseline-description: "init"
    baseline-version: 0
    enabled: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

server:
  port: ${PRODUCT_SERVICE_PORT:8345} 