spring:
  r2dbc:
    url: r2dbc:postgresql://${PG_HOST:localhost}:${PG_PORT:5432}/product
    username: ${PRODUCT_PG_USERNAME:root}
    password: ${PRODUCT_PG_PASSWORD:root}

  sql:
    init:
      mode: always

server:
  port: ${PRODUCT_SERVICE_PORT:8345}