INSERT INTO product (available_quantity, description, name, price, category_id) VALUES
    (100, 'Смартфон с 6.5-дюймовым экраном', 'Smartphone X', 599.99, 
        (SELECT id FROM category WHERE name = 'Electronics')),
    (50, 'Ноутбук с процессором i7', 'Laptop Pro', 1299.99, 
        (SELECT id FROM category WHERE name = 'Electronics')),
    (200, 'Стиральная машина 7 кг', 'Washing Machine 7kg', 499.99, 
        (SELECT id FROM category WHERE name = 'Home Appliances')),
    (80, 'Кофемашина с капучинатором', 'Coffee Maker', 149.99, 
        (SELECT id FROM category WHERE name = 'Home Appliances')),
    (500, 'Футболка хлопковая', 'Cotton T-Shirt', 19.99, 
        (SELECT id FROM category WHERE name = 'Clothing')),
    (300, 'Джинсы слим-фит', 'Slim Fit Jeans', 49.99, 
        (SELECT id FROM category WHERE name = 'Clothing')),
    (150, 'Бестселлер по саморазвитию', 'Self-Development Book', 24.99, 
        (SELECT id FROM category WHERE name = 'Books')),
    (100, 'Фантастический роман', 'Sci-Fi Novel', 29.99, 
        (SELECT id FROM category WHERE name = 'Books')),
    (400, 'Мягкая плюшевая игрушка', 'Plush Toy', 14.99, 
        (SELECT id FROM category WHERE name = 'Toys')),
    (250, 'Конструктор для детей', 'Building Blocks', 39.99, 
        (SELECT id FROM category WHERE name = 'Toys'));
