-- ALTER SEQUENCE payment_id_seq RESTART WITH 1;
-- TRUNCATE TABLE payment;

DROP TABLE IF EXISTS payment CASCADE;
DROP TABLE IF EXISTS flyway_schema_history CASCADE;
DROP SEQUENCE IF EXISTS payment_seq;