global:
  scrape_interval: 15s  # Интервал сбора метрик
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # - job_name: 'microservices'
  #   metrics_path: '/actuator/prometheus'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets:
  #         - 'localhost:8222'
  #         - 'localhost:8090'
  #         - 'localhost:8257'
  #         - 'localhost:8633'
  #         - 'localhost:9324'
  #         - 'localhost:8345'

  - job_name: 'microservices'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets:
          - '172.21.218.219:8222'  # API Gateway
          - '172.21.218.219:8090'  # Customer Service
          - '172.21.218.219:8257'  # Notification Service
          - '172.21.218.219:8633'  # Order Service
          - '172.21.218.219:9324'  # Payment Service
          - '172.21.218.219:8345'  # Product Service

  - job_name: 'kafka'
    static_configs:
      - targets: ['localhost:9092']
