global:
  scrape_interval: 15s # Интервал сбора метрик
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["docker.internal.host:9090"]

  - job_name: 'jmeter'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.0.107:9270']

  - job_name: "microservices"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets:
          - "192.168.10.100:8090" # Customer Service
          - "192.168.10.100:8257" # Notification Service
          - "192.168.10.100:8633" # Order Service
          - "192.168.10.100:9324" # Payment Service
          - "192.168.10.100:8345" # Product Service

  - job_name: "kafka"
    static_configs:
      - targets: ["docker.internal.host:9092"]
