spring:
    datasource:
        url: jdbc:postgresql://${PRODUCT_PG_HOST:localhost}:${PRODUCT_PG_PORT:5432}/${PRODUCT_PG_DATABASE:product}
        username: ${PRODUCT_PG_USERNAME:root}
        password: ${PRODUCT_PG_PASSWORD:root}
    flyway:
        url: jdbc:postgresql://${PRODUCT_PG_HOST:localhost}:${PRODUCT_PG_PORT:5432}/${PRODUCT_PG_DATABASE:product}
        user: ${PRODUCT_PG_USERNAME:root}
        password: ${PRODUCT_PG_PASSWORD:root}
        locations: classpath:db/migration
    
    application:
        name: product-service

server:
    port: ${PRODUCT_SERVICE_PORT:8345}
