CREATE TABLE IF NOT EXISTS payment (
    id SERIAL PRIMARY KEY,
    amount DECIMAL(38,2) NOT NULL,
    payment_method VARCHAR(50) NOT NULL,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
