spring:
    application:
        name: config-server
    profiles:
        active: native
    
    cloud:
        config:
            server:
                native:
                    search-locations: classpath:/configurations/ # path where configurations will be stored
#                 # git:
#                 #     uri: ${GIT_URI}
#                 #     username: ${GIT_USERNAME}
#                 #     password: ${GIT_PASSWORD}

server:
    port: ${CONFIG_SERVER_PORT:8888}

    